### ISSUE TITLE
wrong lpeg.V signature

### ISSUE THREAD

**Issue by jlaurens** [LuaCATS/lpeg#14]
Not only string and integers.

**Comment by Josef-Friedrich** [comment]
Could you please be more specific

**Comment by jlaurens** [comment]
From the documentation "The call lpeg.V(v) creates a pattern that represents the nonterminal (or variable) with index v in a grammar."
"v" is the index in a table, it can be a string, a number, a boolean, a function, everything that is not nil.

BTW, `any` contains `nil`.

**Comment by Josef-Friedrich** [comment]
Thank you for the clarification!

Could you please submit a PR?
