### ISSUE TITLE
version

### ISSUE THREAD

**Issue by jlaurens** [LuaCATS/lpeg#15]
a string not a function

**Comment by Josef-Friedrich** [comment]
Could you please be more specific

**Comment by jlaurens** [comment]
The documentation reads:

lpeg.version

A string (not a function) with the running version of LPeg.

**Comment by Josef-Friedrich** [comment]
Thank you for the clarification. I was on a version 1.0.2

Version 1.1.0

https://github.com/roberto-ieru/LPeg/blob/e58f9bb289b1aa5cd4c96c26cccd0f69461e8436/test.lua#L49-L50

Version 1.0.2

https://github.com/roberto-ieru/LPeg/blob/d9f83dded93a35fb333c4e1bd371c401f7129fd1/test.lua#L51-L52

**Comment by Josef-Friedrich** [comment]
![version 1.1.0 ](https://github.com/user-attachments/assets/ee6d85cc-d8b7-480b-83d3-c1a4062b70eb)

**Comment by Josef-Friedrich** [comment]
version 1.0.2

![version 1.0.2](https://github.com/user-attachments/assets/7403559b-fc88-4545-972a-6ed679a96e7c)

**Comment by Josef-Friedrich** [comment]
version 1.1.0

![version 1.1.0](https://github.com/user-attachments/assets/1641ff8a-b6ed-451c-a5e6-46205c7de2dd)
